Debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,14 +27,12 @@ jobs:
         if: steps.result_cache.outputs.cache-hit != 'true'
         run: cd test/scripts && expect script.exp Linux.sh
       - name: Debug environment
-        run: 'echo "PATH: $PATH"\necho "Contents of .bashrc:"\ncat ~/.bashrc\necho "Sourcing .bashrc..."\nsource ~/.bashrc\necho "PATH after sourcing .bashrc: $PATH"\nwhich asdf || echo "asdf not found in PATH"'
+        run: 'echo "PATH: $PATH"\necho "Contents of .bashrc:" && cat ~/.bashrc && echo "Sourcing .bashrc..."\nsource ~/.bashrc && echo "PATH after sourcing .bashrc: $PATH"\nwhich asdf || echo "asdf not found in PATH"\necho "ASDF_DIR: $ASDF_DIR"'
       - name: Generate an app and start the server
         if: steps.result_cache.outputs.cache-hit != 'true'
         env:
           BASH_ENV: ~/.bashrc
-        run: |
-          source ~/.bashrc
-          make -f test/scripts/Makefile
+        run: source ~/.bashrc\nexport PATH="$HOME/.asdf/bin:$PATH"\n. "$HOME/.asdf/asdf.sh"\nwhich asdf || echo 'asdf not found in PATH'\nmake -f test/scripts/Makefile
         shell: bash --login {0}
       - name: Check HTTP status code
         if: steps.result_cache.outputs.cache-hit != 'true'
